### PR TITLE
ci: use self-hosted runner provided by the CNCF

### PR DESCRIPTION
**Pull request by beeme1mr**

### CODE REVIEW

**Review by toddbaert — APPROVED** [review]

**Comment by beeme1mr** [comment]
We're now getting permission denied when attempting to mark the git directory as safe for [nx-set-sha](https://github.com/nrwl/nx-set-shas?tab=readme-ov-file#self-hosted-runners).

@jeefy any idea?

**Comment by jeefy** [comment]
I kind of nudged it along, that error was because it was trying to modify the git config in `/etc` since the `--system` flag was set.

Now the next step looks like it assumes `node` is installed which isn't the case in the runner image. Might make sense to have the `actions/setup-node` step be before `nx-set-shas` :) I'll try that next and see how it does.

**Comment by jeefy** [comment]
Don't know whether it's actually passing or not, but each step looks to be completing successfully. :) Something to look at after the weekend.

**Comment by beeme1mr** [comment]
Awesome, thanks. Have a great weekend.

**Pull request merged**
