### PR TITLE
Update demo

### PR DESCRIPTION
**Pull request by toddbaert**

### CODE REVIEW

**Comment by agardnerIT** [comment]
FYI

```
git clone https://github.com/open-feature/playground
cd playground
docker compose up
```
Then after more than 5mins (!) `[+] Building 323.0s (16/18)`

It errors.
```
[+] Running 6/6
 - Network playground_default              Created                                                                                                                                                                  0.1s 
 - Volume "playground_flagd-socket"        Created                                                                                                                                                                  0.0s
 - Container playground-go-feature-flag-1  Created                                                                                                                                                                  0.4s 
 - Container playground-jaeger-1           Created                                                                                                                                                                  0.4s 
 - Container playground-flagd-1            Created                                                                                                                                                                  0.4s 
 - Container playground-demo-1             Created                                                                                                                                                                  0.1s
Attaching to playground-demo-1, playground-flagd-1, playground-go-feature-flag-1, playground-jaeger-1
Error response from daemon: Ports are not available: exposing port TCP 0.0.0.0:8013 -> 0.0.0.0:0: listen tcp 0.0.0.0:8013: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.
```

**Comment by beeme1mr** [comment]
It looks like you were already running a service that listened on port 8013. Were you running another instance of flagd at the time?

**Comment by toddbaert** [comment]
> Then after more than 5mins (!)

Ya, you can see the value in a docker container existing already know I'm sure!

But I agree... the error message seems to suggest it can't forward to your local port 8013 because it's already bound by another process.

**Comment by agardnerIT** [comment]
Yes, my bad. I needed more sleep. Demo is working after I stopped the other flagd :)

Great work!

A few things I've noticed that are probably on your list already and these are FYI only:

1) Logging in does an `alert` then logs in successfully.
2) Switching from `flagd` to `env` or `go-feature-flag` removes the editor and I can't get it back
3) Framework doesn't trim. `defaultVariant: 'green '` (notice intentional space after `green`) doesn't change to default (I noticed a fallback of `#000000` in YouTube demo vids).
4) Similar to above, a misspelling doesn't fallback either: `defaultVariant: 'freen'`
4) The tour alignment / highlighting is off for some "steps" on Safari (see below)
5) Jaeger is deployed and tracing is available (this is fantastic) but it isn't mentioned in the tutorial meaning it's just overhead on the demo as a user wouldn't know that it's there.

image

image

**Comment by agardnerIT** [comment]
Online demo: https://killercoda.com/agardnerit/scenario/openfeature-demo

**Review by beeme1mr — APPROVED** [review]

**Pull request merged**
